### ISSUE TITLE
load()could not be fired

### ISSUE THREAD

**Issue by funkster047** [Farcrada/DiscordPlugins#110]
### Describe the bug

This error appears whenever I open discord and it doesn't show up in plugins.

### Expected behavior

To properly load plugin and show it in plugins.

### To reproduce

Open Discord

### Screenshots

<img width="452" alt="code" src="https://user-images.githubusercontent.com/115331053/194683876-3297b920-0d33-4073-81b0-c6f5baa9fe8e.png">

### OS version

Windows 10

### Discord version

Stable 151638 (3ce0196)

### BetterDiscord version

Host 1.0.9006

### Plugin version

9.3.7

**Comment by Farcrada** [comment]
This was fixed in https://github.com/Farcrada/DiscordPlugins/commit/9d999ac83a19ecee70aee19838ef3d34c5602b9c

Unfortunately this means you'll need to re-download the plugin: https://raw.githubusercontent.com/Farcrada/DiscordPlugins/master/Double-click-to-edit/DoubleClickToEdit.plugin.js (save the page as: `DoubleClickToEdit.plugin.js` without the `.txt`)
