### ISSUE TITLE
Loop Updating Bug

### ISSUE THREAD

**Issue by sxnfulv2** [Farcrada/DiscordPlugins#17]
Whenever this plugin updates, I can click the button at the top of my discord to auto-update, but like 30 minutes later, it appears again. A temporary fix I've found is to manually download the plugin again, but i'd like to just be able to easily update it via the discord client.

**Comment by Farcrada** [comment]
On it, am looking into it. Also in the middle of updating the repo to facilitate more plugins.

**Comment by Farcrada** [comment]
I have merged all the files, I fucked up the URL in the preparation, so fuck me I guess, so I'd love to hear if it's fixed now.

I suspect this happened because it couldn't actually update but did find a new version? Though why wouldn't it just download the new update? I recognize the problem, sometimes does it once or twice with a new plugin, but I always suspected it was my own fault. Well, it still is, but you know.

**Comment by Farcrada** [comment]
It seems that was the issue. If it still persists please let me know.
