### ISSUE TITLE
[ChannelPermissions] ChatUserIDsRedux `white-space` css interference 

### ISSUE THREAD

**Issue by lolpowerluke** [Farcrada/DiscordPlugins#30]
plugin doesnt work correctly with the ChatUserIDRedux plugin by Arashiryuu

Steps to reproduce the behaviour:
1. download the mentioned plugin
2. enable it
3. go to server to check popup
4. switch servers and check popup again

**Expected behaviour**
after enable it works, but the popup looks like the image
after server switch, popup doesnt show up anymore

![image](https://user-images.githubusercontent.com/47672899/122790671-d5570f00-d2b8-11eb-83f5-ef414a3a364f.png)

 - OS: Windows 10 (home) 64 Bit
 - Plugin version: 3.5.0
 - Better Discord (BD) Version 1.1.1

**Comment by Farcrada** [comment]
Found the issue: https://github.com/Arashiryuu/crap/blob/bae85338e7bd7070bc27533f3383e4143b0d359f/ToastIntegrated/ChatUserIDsRedux/ChatUserIDsRedux.plugin.js#L277

I'll open a new issue to see if this is a remnant (since I cannot seem to find a reason why it would be needed).

**Comment by Farcrada** [comment]
For now; I suppose you can manually delete that CSS block; unfortunate. Let me see if I can come up with something.

**Comment by lolpowerluke** [comment]
is there a way I can fix the issue for the onSwitch function?
cause if I switch servers or channels it doesnt show up anymore

**Comment by lolpowerluke** [comment]
well, I was able to kind of fix it by changing the onSwitch function to just this
![image](https://user-images.githubusercontent.com/47672899/122961973-3c41fa00-d385-11eb-90d5-d67b27438472.png)
but now it bugs out and keeps showing it at the top of the application
![image](https://user-images.githubusercontent.com/47672899/122962160-6dbac580-d385-11eb-832e-2469050a86c3.png)

**Comment by lolpowerluke** [comment]
ok, update, I changed it to this and it works most of the time (it stopped working once but after I switched channels again it started working again)
![image](https://user-images.githubusercontent.com/47672899/122963338-75c73500-d386-11eb-873e-05b8785424ef.png)

**Comment by Farcrada** [comment]
Are you running any other plugins? Because this seems like a completely separate issue.


> 
> 
> ok, update, I changed it to this and it works most of the time (it stopped working once but after I switched channels again it started working again)
> ![image](https://user-images.githubusercontent.com/47672899/122963338-75c73500-d386-11eb-873e-05b8785424ef.png)
> also, I'm not sure if everything I did here was correct, so if I'm doing something wrong, feel free to tell me

What you did here makes no sense. You (if there're any tool-tips currently closing (most likely none)) stop the plugin for as many times as there are currently closing plugins and then (attempt) to start the plugin again. Which recreates the cache (heavy task) and adds a duplicate event listener.

As you might've noticed that for loop does not have any curly brackets `{ }` which means only `this.stop();` is executed. After the for loop it calls `this.start();`  once and then continues the `onSwitch()` function.



> 
> 
> is there a way I can fix the issue for the onSwitch function?
> cause if I switch servers or channels it doesnt show up anymore

What exactly do you mean with "it doesn't show up anymore"? Do you mean that the tool tip shows up but as soon as you switch server/channel it stops working?

If you press `Ctrl + Shift + I` and click `console` at the top; are there any red blobs that show up (console errors)? Could you post those if they're there?

**Comment by Farcrada** [comment]
I ask you open a new issue with the details requested above. Prevents unnecessary clutter. ❤️
