### ISSUE TITLE
[DoubleClickToEdit] Allow you to edit other people's messages as well

### ISSUE THREAD

**Issue by NgxKing** [Farcrada/DiscordPlugins#56]
It will allow you to edit other people's messages too only if you have a role with permission Manage_Message

**Comment by Farcrada** [comment]
Was this intended as a `enhancement`? Or did you misplace it and it had to be a `bug`?

If it was the former, that would not be possible as Discord does not possess that functionality. Mainly because message integrity would simply fall through and reliability of any message would be compromised.

If it was the latter: I am unable to reproduce the error, is that why you closed it? Did it have to do with another plugin?

**Comment by NgxKing** [comment]
> Was this intended as an `enhancement`? Or did you misplace it and it had to be a `bug`?
> 
> If it was the former, that would not be possible as Discord does not possess that functionality. Mainly because message integrity would simply fall through and the reliability of any message would be compromised.
> 
> If it was the latter: I am unable to reproduce the error, is that why you closed it? Did it have to do with another plugin?

Well, it was intended as an `enhancement` but I just realized that you can't edit other's messages then I closed it. I have wasted your time on a dumb mistake. Sorry!

**Comment by Farcrada** [comment]
Don't worry! All good!

IF you had anything else in mind in the future, don't hesitate to open an issue! ❤️
